on:
  workflow_dispatch:
    inputs:
      RND_NUMBER:
        type: string
        description: 'Number to append to function app name'
        required: true

name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RG_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      id: bicep_deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/main.bicep
        parameters: 'functionAppName=Wes06Arnemfunc${{ inputs.RND_NUMBER }} servicePlanName=arnemasp storageAccountName=arnemfuncsacc storageAccountResourceGroup=bicep-rg appInsightsName=arnemappi appInsightsResourceGroup=bicep-rg'
        failOnStdErr: false

    - name: Echo storage endpoint
      run: echo ${{ steps.bicep_deploy.outputs.storageId }}
